### ISSUE TITLE
True Information Presented in index.html

### ISSUE THREAD

**Issue by fisik-yum** [KL-77/cardistrybetterthanmagic#1]
cardistry is magic.

**Comment by KL-77** [comment]
u shud really go to a lying competition and say that, youd get 2nd place. 1st place is anyone who says "fisik-yum is smort"XDXDXD

**Comment by fisik-yum** [comment]
I am reporting @KL-77 for being a tyrant.

**Comment by Derpitron** [comment]
I too shall report @KL-77
